{
 "title": "NodeProcess",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_process_cpu_usage_percent,instance)"
    }
   },
   { "name": "top", "label": "top", "query": "5, 10, 20, 50" }
  ]
 },
 "panels": [
  {
   "title": "进程CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(${top},node_process_cpu_usage_percent{instance=\"${instance}\"})",
     "legendFormat": "{{name}} - Pid: {{pid}}"
    }
   ]
  },
  {
   "title": "进程内存",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(${top},node_process_memory_usage_percent{instance=\"${instance}\"})",
     "legendFormat": "{{name}} - Pid: {{pid}}"
    }
   ]
  },
  {
   "title": "进程文件打开数",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(${top},node_process_open_files_count{instance=\"${instance}\"})",
     "legendFormat": "{{name}} - Pid: {{pid}}"
    }
   ]
  },
  {
   "title": "进程磁盘读写IO",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(${top},rate(node_process_read_bytes_total{instance=\"${instance}\"}[1m]))",
     "legendFormat": "Read: {{name}} - Pid: {{pid}}"
    },
    {
     "expr": "topk(${top},rate(node_process_read_bytes_total{instance=\"${instance}\"}[1m]))",
     "legendFormat": "Write: {{name}} - Pid: {{pid}}"
    }
   ]
  }
 ]
}